### ISSUE TITLE
Load model config from yaml file

### ISSUE THREAD

**Issue by mozharovsky** [formermagic/formerbox#2]
Use yaml config file to setup model configs (instead of passing a ton of parameters through command line).

Ideally, I'd like to have flexible configs similar to Rasa's pipeline config ([example](https://github.com/RasaHQ/financial-demo/blob/master/config.yml)). 

```yaml
model:
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 24
  intermediate_size: 3072
```
